{% set name = "clang" %}
{% set version = "8.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: http://releases.llvm.org/{{ version }}/llvm-{{ version }}.src.tar.xz
    folder: llvm
  - url: http://releases.llvm.org/{{ version }}/cfe-{{ version }}.src.tar.xz
    folder: llvm/tools/clang
  - url: http://releases.llvm.org/{{ version }}/clang-tools-extra-{{ version }}.src.tar.xz
    folder: llvm/tools/clang/tools/extra
  - path: setup.py

build:
  number: 0

requirements:
  build:
    - python
  host:
    - python
  run:
    - python

outputs:
  - name: libclang
    script: build_lib.sh
    requirements:
      build:
        - ca-certificates
        - cmake
        - make
        - python
        - zlib
        - {{ compiler('cxx') }}
    test:
      commands:
        - clang-format --version
        - clang-tidy --version
    about:
      summary: "Clang library and format/tidy packages"
  - name: clang
    script: build_py.sh
    requirements:
      host:
       - python
       - pip
      run:
        - python
        - {{ pin_subpackage('libclang', exact=True) }}
    test:
      imports:
        - clang.cindex
    about:
      summary: "Python bindings for clang library"

about:
  home: http://llvm.org/
  license: Apache-2.0
  doc_url: http://llvm.org/
  dev_url: http://llvm.org/

extra:
  recipe-maintainers:
    - teju85
